### ISSUE TITLE
Refreshes page (sometimes) leading to issues

### ISSUE THREAD

**Issue by Aerozol** [phw/musicbrainz-magic-tagger-button#4]
When I use an import script (for instance the Bandcamp import script), the MB page sometimes refreshes right after opening, causing the import to lose the data. This does not always happen… I believe it does always happen when Picard is open, but occasionally also when it is not.
Disabling the magic tagger button script stops it from refreshing/lets me import the release.
I haven’t tested to see if it’s because of how it interacts with my other scripts, let me know if you need me to check anything.

**Comment by phw** [comment]
Which page is it that reloads? The edit pages actually are supposed to be excluded from the tagger button script, there should be no reload happening there.

Also make sure you are using the latest version 0.7.6 of this script and not an older one.

**Comment by Aerozol** [comment]
Ah, maybe it’s because I’m on beta and that’s not excluded?
It’s reloading ‘https://beta.musicbrainz.org/release/add’ (with the seeded data) to ‘https://beta.musicbrainz.org/release/add?tport=8000’
I’m on 0.7.6

**Comment by phw** [comment]
Beta should be excluded the same. Which browser and user script manager are you using?

**Comment by phw** [comment]
Oh, it was indeed beta. The exclusion rules where specifying the subdomains wrong.

**Comment by Aerozol** [comment]
Thanks phw!! <3
